version: "3"

services:
  gui:
    build:
      context: ./
      dockerfile: docker/dockerfiles/webserver/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-${WEBSERVER_NAME}'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:8080"