version: "3"

# NETWORK
# The default network used is Docker's built-in 'host' (run docker network ls)
# This allows the container to access other containers via the host machine

services:
  gui:
    tty: true
    build:
      context: ./
      dockerfile: docker/dockerfiles/webserver/Dockerfile
    container_name: '${COMPOSE_PROJECT_NAME}-${WEBSERVER_NAME}'
    restart: 'always'
    entrypoint: /docker-entrypoint.sh
    volumes:
      - ./docker/dockerfiles/webserver/docker-entrypoint.sh:/docker-entrypoint.sh
      - .:/app
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:8080"