#!/bin/bash

# Set path to root directory
# shellcheck disable=SC2164
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd "${SCRIPT_PATH}" && cd ..

######################################
#
# Step 1: Add configuration files (Docker and ViteJS)
#
######################################

DOCKER_ENV_FILE_EXAMPLE=./.env.example
DOCKER_ENV_FILE=./.env

VITE_ENV_FILE_EXAMPLE=./vite/.env.example
VITE_ENV_FILE=./vite/.env

cp $DOCKER_ENV_FILE_EXAMPLE $DOCKER_ENV_FILE
cp $VITE_ENV_FILE_EXAMPLE $VITE_ENV_FILE

######################################
#
# Step 2: Prepare shared folders
#
######################################

# Create synced docker volumes
mkdir -p docker/volumes/mysql

# Docker needs execute permissions for the entrypoint files
chmod g+x docker/entrypoint/php-fpm-entrypoint.sh

