#!/bin/bash

# TODO: Work in progress

# Set path to root directory
# shellcheck disable=SC2164
SCRIPT_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd "${SCRIPT_PATH}" && cd ..

#########################
# Make sure that the env files exist
#########################

DOCKER_ENV_FILE=./.env

# Make sure that docker .env file exists
if ! test -f "$DOCKER_ENV_FILE"; then
    echo "There is no $DOCKER_ENV_FILE file, please create one from .env.example and restart installation..."
    exit
fi

#########################
# Prepare shared folders
#########################

# Create synced docker volumes
mkdir -p docker/volumes/mysql

# Docker needs execute permissions for the entrypoint files
chmod g+x docker/entrypoint/php-fpm-entrypoint.sh

